export { default as Home } from "./Home/Home"
export { default as Error } from "./Error/Error"
export { default as Activities } from "./Activities/Activities"
export { default as BMI } from "./BMI/BMI"
export { default as Pressure } from "./Pressure/Pressure"
export { default as Covid19 } from "./Covid19"
export { default as User } from "./User"
export { default as Settings } from "./Settings/Settings"
